################ Japanese language ##################
[ja]
languageName = "æ—¥æœ¬èª ğŸ‡¯ğŸ‡µ"
languageCode = "ja"
contentDir = "content/japanese"
weight = 1

################ English language ##################
[en]
languageName = "EN ğŸ‡ºğŸ‡²"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
